return {
  dictionary = {
    ["en-US"] = {
      "MLSys",
      "DNN",
      "DNNs",
      "NSDI",
      "OSDI",
      "SOSP",
      "ISCA",
      "HPCA",
      "ASPLOS",
      "ICLR",
      "NeurIPS",
      "ICML",
      "CVPR",
      "AAAI",
      "EMNLP",
      "USENIX",
      "ImageNet",
      "tradeoff",
      "Jae-Won",
      "MLOps",
      "KubeFlow",
      "DeepSpeed",
      "Megatron",
      "microbatch",
      "docstring",
      "Mosharaf",
      "Huggingface",
      "MAB",
      "CloudLab",
    }
  }
}
